"""Render docs/CHECKPOINT-2.md from data/build-report.json.

Every number in the checkpoint document comes from the build report; nothing
is typed by hand. Also fills the `books` columns of docs/AMBIGUITY-REVIEW.md.

  python tools/report_checkpoint.py
"""

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
R = json.loads((ROOT / "data" / "build-report.json").read_text())


def n(x):
    return f"{x:,}".replace(",", " ")


def pct(x):
    return f"{100 * x:.1f} %"


def kb(x):
    return f"{x / 1000:,.0f} KB".replace(",", " ")


def mb(x):
    return f"{x / 1e6:.2f} MB"


def table(head, rows):
    out = ["| " + " | ".join(head) + " |", "|" + "|".join("---" for _ in head) + "|"]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(out)


def main():
    st = R["ngram"]["stats"]
    L = []
    L.append("# Checkpoint 2 — corpus pipeline\n")
    L.append("Generated by `tools/report_checkpoint.py` from `data/build-report.json`.\n")

    L.append("## Budgets (CLAUDE.md §6)\n")
    b = R["builds"]
    L.append(table(["Artifact", "Budget", "Measured", "Status"], [
        ["`lexicon-lite.bin` gzipped", "≤ 2 MB", f"{mb(b['lite']['gzip'])} ({mb(b['lite']['bytes'])} raw)",
         "within" if b["lite"]["within_budget"] else "**MISSED**"],
        ["`lexicon-full.bin` gzipped", "≤ 8 MB", f"{mb(b['full']['gzip'])} ({mb(b['full']['bytes'])} raw)",
         "within" if b["full"]["within_budget"] else "**MISSED**"],
        ["`engine/` gzipped", "≤ 30 KB", f"{R['engine_gzip_so_far']} B — only `constants.js` exists", "not measurable yet (step 4)"],
        ["Runtime heap, lite", "≤ 25 MB", f"estimate {mb(b['lite']['est_runtime_bytes'])}: file + offset table",
         "estimate only; measured in step 4"],
    ]))
    L.append("")
    L.append(table(["Build", "Words", "Bigrams", "Bigram id width"], [
        ["lite", n(b["lite"]["words"]), n(b["lite"]["bigrams"]), "u32" if b["lite"]["wide_ids"] else "u16"],
        ["full", n(b["full"]["words"]), n(b["full"]["bigrams"]), "u32" if b["full"]["wide_ids"] else "u16"],
    ]))
    L.append("\nFull-build size grid (the chosen build is the largest word count that "
             "still fits ≥ 2 M bigrams, then the most bigrams):\n")
    L.append(table(["Words", "Bigrams", "Raw", "Gzipped", "≤ 8 MB"],
                   [[n(g["words"]), n(g["bigrams"]), mb(g["bytes"]), mb(g["gzip"]), "yes" if g["fits"] else "no"]
                    for g in R["full_grid"]]))

    L.append("\n## Sources and token counts\n")
    rows = []
    lic = {"books": "MIT", "news": "Apache-2.0", "telegram": "Apache-2.0"}
    name = {"books": "uz-books-v2 `lat`", "news": "uz-crawl `news`", "telegram": "uz-crawl `telegram_blogs`"}
    for s in ("books", "news", "telegram"):
        x = st.get(s)
        if not x or not x.get("docs"):
            continue
        rows.append([name[s], lic[s], x.get("shards", 0), n(x["docs"]), f"{n(x['docs_dropped'])} ({pct(x['docs_dropped'] / x['docs'])})",
                     n(x["words_seen"]), n(x["words_kept"])])
    tot_kept = sum(x.get("words_kept", 0) for x in st.values())
    rows.append(["**total**", "", "", "", "", n(sum(x.get("words_seen", 0) for x in st.values())), f"**{n(tot_kept)}**"])
    L.append(table(["Source", "Licence", "Shards", "Documents", "Dropped (> 5 % outside charset)", "Word tokens seen",
                    "Word tokens counted"], rows))
    L.append("\nWord tokens = Uzbek-charset tokens after normalization; protected spans "
             "(URLs, mentions, letters glued to digits, mixed case) are not counted.\n")

    a = R["admission"]
    L.append("## Vocabulary\n")
    L.append(table(["", "Count"], [
        ["Unigram types, all", n(R["ngram"]["unigram_types_all"])],
        ["Unigram types, count ≥ 2 (hapax dropped)", n(R["ngram"]["unigram_types_ge2"])],
        ["Admitted to the lexicon (§9.6)", n(a["admitted"])],
        ["— carrying a mark (ş ç ö ğ ʼ)", n(a["admitted_marked"])],
        ["— unmarked, attested in books", n(a["admitted_unmarked"])],
        *[[f"Rejected: `{k}`", n(v)] for k, v in sorted(a["rejected_by_reason"].items(), key=lambda kv: -kv[1])],
        ["Rejected forms merged into their marked word (rule 6)", n(a["merged"])],
        ["Token mass of merged forms", n(a["merged_token_mass"])],
        ["Bigram types (over the provisional vocabulary)", n(R["ngram"]["bigram_types_all"])],
        ["Bigram types with count ≥ 2", n(R["ngram"]["bigram_types_ge2"])],
        ["Provisional vocabulary (bigram id space)", n(R["ngram"]["provisional_vocab"])],
        ["Full-build words with no bigram id (lose bigrams only)", n(R["full_words_without_bigram_ids"])],
    ]))

    L.append("\n## Coverage\n")
    L.append("Share of counted tokens (forms with count ≥ 2) whose canonical form is a lexicon word. "
             "Measured on the training counts themselves, so it is an upper bound, not a held-out number.\n")
    rows = []
    for build in ("lite", "full"):
        for s in ("books", "news", "telegram"):
            c = R["coverage"][build][s]
            rows.append([build, s, pct(c["in_lexicon"]), pct(c["stripped_variant_of_lexicon_word"])])
    L.append(table(["Build", "Source", "In lexicon", "Stripped variant of a lexicon word (correctable)"], rows))

    L.append("\n## How the crawl was typed\n")
    dc = R["doc_classes"]
    classes = ["latin_marked", "latin_bare", "cyr_uz", "cyr_ru_layout", "short"]
    L.append(table(["Source"] + classes, [[s] + [n(dc.get(s, {}).get(c, 0)) for c in classes] for s in ("news", "telegram")]))
    L.append("\n`latin_bare` = Latin, never marks ö/ğ. `cyr_ru_layout` = Cyrillic with none of ў қ ғ ҳ. "
             "`short` = under 20 word tokens, not classified.\n")

    q = R["q19_cost"]
    L.append("## Cost of “valid tokens are never rewritten” (Q19)\n")
    L.append("Tokens in the two keyboard-limited document classes, against the lite build. *Blocked* = the token "
             "is itself a word, and a marked sibling with the same key is ≥ 10× more frequent; §5.1 keeps it. "
             "*Corrected* = the token is not a word and a marked sibling exists. Intent cannot be known from "
             "counts; *blocked* is an upper bound on corrections the rule forgoes.\n")
    rows = []
    for k, label in (("latin_bare_docs", "Latin, no ö/ğ"), ("cyr_ru_layout_docs", "Cyrillic, Russian layout")):
        x = q[k]
        rows.append([label, n(x["tokens"]), f"{n(x['blocked'])} ({pct(x['blocked'] / x['tokens']) if x['tokens'] else '–'})",
                     f"{n(x['corrected'])} ({pct(x['corrected'] / x['tokens']) if x['tokens'] else '–'})"])
    L.append(table(["Documents", "Tokens", "Blocked", "Corrected"], rows))
    for k, label in (("latin_bare_docs", "Latin"), ("cyr_ru_layout_docs", "Cyrillic (shown in canonical Latin)")):
        L.append(f"\nTop blocked, {label}: " + ", ".join(f"`{w}`→`{g}` ×{c}" for w, g, c in q[k]["blocked_top"][:15]))

    p = R["partial_mark_forms"]
    L.append("\n## Crawl-only partially marked forms\n")
    L.append(f"Forms with a mark, absent from books, admitted from crawl under rule 1, whose fully marked sibling "
             f"is ≥ 10× more frequent: **{n(p['count'])}** forms, {n(p['token_mass'])} tokens, "
             f"{n(p['in_lite'])} of them inside the lite build. Under §5.1 each is a valid token that blocks its "
             f"own correction.\n")
    L.append(", ".join(f"`{w}` ({n(c)}) vs `{g}` ({n(cg)})" for w, g, c, cg in p["top"][:20]))

    i = R["informal"]
    L.append("\n## Informal passthrough set and risk list (telegram_blogs, lite build)\n")
    L.append(table(["", "Surface forms (count ≥ 2)"], [
        ["Not a valid token", n(i["surface_forms_ge2_not_valid"])],
        ["— no key match: passes through (invariant-test pool)", n(i["passthrough"])],
        ["— key matches a word: `autocorrect()` would change it (risk list)", n(i["risk"])],
    ]))
    L.append("\nRisk list, most frequent 30 (form ×count → candidates):\n")
    L.append("\n".join(f"- `{s}` ×{c} → {', '.join('`' + h + '`' for h in hits)}" for s, c, hits in i["risk_top"]))
    L.append("\nRisk list, random 30:\n")
    L.append("\n".join(f"- `{s}` ×{c} → {', '.join('`' + h + '`' for h in hits)}" for s, c, hits in i["risk_random"]))
    L.append("\nPassthrough, random 30: " + ", ".join(f"`{s}`" for s, c, _ in i["passthrough_random"]))

    old = ROOT / "data" / "raw" / "build-report-v02-narrow.json"
    if old.exists():
        O = json.loads(old.read_text())
        L.append("\n## Rule 3 as approved (any marks removed) vs. as drafted in SPEC v0.2 (all marks removed)\n")
        L.append("SPEC v0.2 narrowed the stripped-variant test to forms with *every* mark removed, so `boyiça` "
                 "(0.19 % of `böyiça`) and `taminlaş` (0.83 % of `taʼminlaş`) were admitted. This build restores the "
                 "Q17 proposal as approved: any subset of marks removed, for any form.\n")
        oa, na = O["admission"], R["admission"]
        oq, nq = O["q19_cost"], R["q19_cost"]
        L.append(table(["", "v0.2 as drafted", "this build"], [
            ["Admitted", n(oa["admitted"]), n(na["admitted"])],
            ["Rejected as stripped variant below 1 %", n(oa["rejected_by_reason"].get("stripped-variant-below-ratio", 0)),
             n(na["rejected_by_reason"].get("stripped-variant-below-ratio", 0))],
            ["Merged into the marked word", n(oa["merged"]), n(na["merged"])],
            ["Merged token mass", n(oa["merged_token_mass"]), n(na["merged_token_mass"])],
            ["Q19 blocked, Latin no-ö/ğ docs", n(oq["latin_bare_docs"]["blocked"]), n(nq["latin_bare_docs"]["blocked"])],
            ["Q19 corrected, Latin no-ö/ğ docs", n(oq["latin_bare_docs"]["corrected"]), n(nq["latin_bare_docs"]["corrected"])],
            ["Q19 blocked, Russian-layout docs", n(oq["cyr_ru_layout_docs"]["blocked"]), n(nq["cyr_ru_layout_docs"]["blocked"])],
            ["Risk list size (telegram)", n(O["informal"]["risk"]), n(R["informal"]["risk"])],
            ["Lite gzipped", mb(O["builds"]["lite"]["gzip"]), mb(R["builds"]["lite"]["gzip"])],
            ["Full gzipped", mb(O["builds"]["full"]["gzip"]), mb(R["builds"]["full"]["gzip"])],
        ]))

    k = R["whatif_keyboard_variants"]
    L.append("\n## What if: Russian-layout spellings in rule 3 (Q29) — not applied\n")
    L.append("Lite words that are a spelling of a more frequent word with `u`/`k`/`x` standing in for `ö`/`q`/`h` "
             "(possibly with other marks dropped too), rejected if their book count is below the ratio. "
             f"Russian-layout tokens blocked by §5.1 today: {n(k['cyr_ru_layout_blocked_now'])}.\n")
    L.append(table(["Ratio", "Lite words rejected", "Their corpus tokens", "Russian-layout tokens still blocked"],
                   [[pct(x["ratio"]), n(x["lite_forms"]), n(x["token_mass"]), n(x["cyr_ru_layout_blocked_after"])]
                    for x in k["by_ratio"]]))
    for x in k["by_ratio"]:
        L.append(f"\nAt {pct(x['ratio'])}, most frequent: " + ", ".join(
            f"`{w}`→`{g}` ({100 * q:.2f} %)" for w, g, bw, bg, q in x["top"][:18]))
        L.append(f"\nAt {pct(x['ratio'])}, closest to the threshold — check these are not real words: " + ", ".join(
            f"`{w}`→`{g}` ({100 * q:.2f} %)" for w, g, bw, bg, q in x["near_threshold"][:18]))

    v = R["whatif_veto"]
    L.append("\n## What if: never drop a typed mark (Q28) — not applied\n")
    L.append(f"Of {n(v['risk_forms'])} risk-list forms, the most frequent candidate removes a mark or tutuq the "
             f"writer typed (or turns Cyrillic `с` into `ş`) for **{n(v['vetoed'])}**; those would stay unchanged. "
             f"{n(v['still_changed'])} would still be changed.\n")
    L.append("Would be vetoed: " + ", ".join(f"`{s}` ×{c} → `{h}`" for s, c, h in v["vetoed_top"][:20]))
    L.append("\nWould still change: " + ", ".join(f"`{s}` ×{c} → `{h}`" for s, c, h in v["still_changed_top"][:20]))

    L.append("\n## The brief's examples (Python approximation, not the engine)\n")
    L.append("§5.1 readings, then key lookup ranked by frequency only — no bigrams, no evidence term. "
             "It shows what the lexicon alone decides.\n")
    for build in ("lite", "full"):
        rows = []
        for line, res in R["brief_examples"][build]:
            rows.append([f"`{line}`", " ".join(f"`{w}`" + ("" if how != "corrected" else "*") for w, how in res)])
        L.append(f"\n{build} (`*` = corrected, others valid or unchanged):\n")
        L.append(table(["Input", "Output"], rows))

    pc = R["protected_candidates"]
    L.append(f"\n## Protected-word candidates\n\n{n(pc['count'])} forms contain a literal `sh`, `ch` or `gh` "
             f"(full list: `data/protected-words.candidates.tsv`, not yet used). Most frequent: "
             + ", ".join(f"`{w}`" for w in pc["top"]))
    (ROOT / "docs" / "CHECKPOINT-2.md").write_text("\n".join(L) + "\n", encoding="utf-8")

    # Fill book counts into the ambiguity review table.
    path = ROOT / "docs" / "AMBIGUITY-REVIEW.md"
    text = path.read_text(encoding="utf-8")
    rows = R["ambiguity_counts"]["rows"][1:]  # row 0 is the already-ruled `ser`
    out = []
    for line in text.splitlines():
        m = re.match(r"^\| (\d+) \|", line)
        if m and 1 <= int(m.group(1)) <= len(rows):
            cells = line.split("|")
            counts = [str(x[1]) for x in rows[int(m.group(1)) - 1]] + [""] * 3
            # cells: ['', #, input, A, gA, B, gB, C, gC, booksA, booksB, booksC, mark, '']
            for k in range(3):
                cells[9 + k] = f" {counts[k]} " if counts[k] else " "
            line = "|".join(cells)
        out.append(line)
    path.write_text("\n".join(out) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
